### ISSUE TITLE
CUDA out of memory on AQUA server

### ISSUE THREAD

**Issue by mshannon-sil** [sillsdev/silnlp#192]
When running experiments for the NLLB.1.3B.ne_LhrNbt-lbr_Lhr.NT_TOK project, getting the following error during training on NLLB 1.3B with batch size 8:

Traceback (most recent call last):
  File "/usr/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/root/.clearml/venvs-builds/3.8/task_repository/silnlp.git/silnlp/nmt/experiment.py", line 141, in <module>
    main()
  File "/root/.clearml/venvs-builds/3.8/task_repository/silnlp.git/silnlp/nmt/experiment.py", line 137, in main
    exp.run()
  File "/root/.clearml/venvs-builds/3.8/task_repository/silnlp.git/silnlp/nmt/experiment.py", line 39, in run
    self.train()
  File "/root/.clearml/venvs-builds/3.8/task_repository/silnlp.git/silnlp/nmt/experiment.py", line 62, in train
    model.train()
  File "/root/.clearml/venvs-builds/3.8/task_repository/silnlp.git/silnlp/nmt/hugging_face_config.py", line 695, in train
    train_result = trainer.train(resume_from_checkpoint=last_checkpoint)
  File "/root/.clearml/venvs-builds/3.8/task_repository/silnlp.git/.venv/lib/python3.8/site-packages/transformers/trainer.py", line 1500, in train
    return inner_training_loop(
  File "/root/.clearml/venvs-builds/3.8/task_repository/silnlp.git/.venv/lib/python3.8/site-packages/transformers/trainer.py", line 1742, in _inner_training_loop
    tr_loss_step = self.training_step(model, inputs)
  File "/root/.clearml/venvs-builds/3.8/task_repository/silnlp.git/.venv/lib/python3.8/site-packages/transformers/trainer.py", line 2496, in training_step
    self.scaler.scale(loss).backward()
  File "/root/.clearml/venvs-builds/3.8/task_repository/silnlp.git/.venv/lib/python3.8/site-packages/torch/_tensor.py", line 307, in backward
    torch.autograd.backward(self, gradient, retain_graph, create_graph, inputs=inputs)
  File "/root/.clearml/venvs-builds/3.8/task_repository/silnlp.git/.venv/lib/python3.8/site-packages/torch/autograd/__init__.py", line 154, in backward
    Variable._execution_engine.run_backward(
RuntimeError: CUDA out of memory. Tried to allocate 3.07 GiB (GPU 0; 39.59 GiB total capacity; 29.26 GiB already allocated; 3.00 GiB free; 34.71 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF
2023-08-24 10:12:09
Process failed, exit code 1

**Comment by mshannon-sil** [comment]
When I run into this on my machine, running the python command `torch.cuda.empty_cache()` has worked for me. I'll try this on the AQuA server and see if this fixes the problem.

**Comment by mshannon-sil** [comment]
It was determined that the batch sizes just needed to be decreased in order for the experiment to work. In the future, if this message pops up again and reserved memory is much greater than allocated memory, we should look into reducing max_split_size_mb.
